spring.application.name=sb-pg-vector

spring.datasource.url=jdbc:postgresql://localhost:9090/vector_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
